### PR TITLE
cdcacm: Lower usage of magic numbers.

### PR DESCRIPTION
**Pull request by UweBonnes**

### CODE REVIEW

**Comment by compuphase** [comment]
This also makes it easier for platforms that have different endpoint definitions, see PR #735.

**Comment by UweBonnes** [comment]
Test reports are welcome! This PR can do some damage, Perhaps my cursory test did  not show these problems.

**Comment by compuphase** [comment]
I tested the GDB interface, UART interface and TRACESWO, and found no problems. All tests were done on the native BMP 2.1.

**Comment by esden** [comment]
This looks good to me. I have tested it and compared with the original "magic" numbers. Thanks @UweBonnes

**Pull request merged**
