### PR TITLE
STM32F72x/73x support

### PR DESCRIPTION
**Pull request by sambas**
STM32F72x/73x support

### CODE REVIEW

**Comment by UweBonnes** [comment]
https://github.com/UweBonnes/blackmagic/tree/stm32f2_4_7
contains support for F72X and mor fixes. Can you have a look?

**Comment by sambas** [comment]
Yours is better, just having issues to make it fit into stlink. One issue I have, when I stop debugging I have to disconnect/reconnect usb to make it work again. Using F3discovery to debug 722 target

**Comment by hydra** [comment]
i have the same issue as @sambas with regards to having to unplug the bmp.

i solved the 'fitting to stlink target' issue by disabling some probes of some other processors to save flash space.

**Comment by gsmcmullin** [comment]
This support was added in #235

**Pull request closed without merging**
