### PR TITLE
[RFC] Only support buffered flash writes

### PR DESCRIPTION
**Pull request by gsmcmullin**
It has been suggested that buffered writes are better in all cases, for performance and to solve potential alignment problems.

This follows from discussion of #299

### CODE REVIEW

**Comment by ChuckM** [comment]
👍 looks good to me.

**Comment by UweBonnes** [comment]
I think, buffered writes are best in most situation. But we should not drop infrastructure for non-buffered writes

**Comment by UweBonnes** [comment]
Thinking again, I think it is okay to drop infrastructure for non-buffered writes.

Probably the f->erased values is also no more needed and should be removed from target_internal.h.

**Comment by UweBonnes** [comment]
Another missthinking. Argh. f->erased is needed for setting up the buffer.

**Pull request merged**
