### PR TITLE
stlink: Announce 124 kiB flash size in DFU to commplement #204.

### PR DESCRIPTION
**Pull request by UweBonnes**
STLinkV2-1 has F103CB on board! F103C8 can use upper flash with hopefully
acceptable error rate.

### CODE REVIEW

**Comment by UweBonnes** [comment]
Another approach would be to announce the amount of flash found in the flashsize register and leave it up to the user to force dfu to write not flash not announced...

**Comment by gsmcmullin** [comment]
Please rebase this as it conflicts with your changes in #206 (merged).  I like your suggestion of reporting the flash size in the fuse registers and force the user to override if they choose to.

**Comment by UweBonnes** [comment]
The pull request should be rebased now and the DFU String is taken from the  FLASH_SIZE register minus the bootloader area.

If you  look at the old calculation of max_address, the code did not what was intended...

**Comment by UweBonnes** [comment]
The DFU update string now reflects device read or bootloader write protection, indication 0 available pages.

**Comment by UweBonnes** [comment]
Up to now, dfu-utils at https://sourceforge.net/p/dfu-util/dfu-util/ci/master/tree/ does not erase flask pages above the l,imit given in the dfu-string. https://sourceforge.net/p/dfu-util/tickets/44/ helps in that situation.

**Pull request merged**
