### PR TITLE
Add support for NXP LPC802, LPC804, LPC832 and LPC834

### PR DESCRIPTION
**Pull request by compuphase**
This pull request adds support for the NXP LPC802, LPC804, LPC832 and LPC834 MCU series.

### CODE REVIEW

**Comment by UweBonnes** [comment]
The designer is not AP_DESIGNER_SPECULAR? Can you post a hosted "blackmagic -t " run so the romtable essantial get visible?

**Comment by compuphase** [comment]
INFO: Open USB 056a:00d4 class  0 failed
BMP hosted v1.7.1-129-g8b7d789-dirty
 for ST-Link V2/3, CMSIS_DAP, JLINK and LIBFTDI/MPSSE
Using 1d50:6018 7BB180B4 Black Sphere Technologies
 Black Magic Probe  v1.7.1-129-g8b7d789-dirty
Running in Test Mode
Target voltage: 3.1V Volt
Speed set to  3.2727 MHz for SWD
DPIDR 0x0bc11477 (v1 MINDP rev0)
RESET_SEQ failed
AP   0: IDR=04770031 CFG=00000000 BASE=e00ff003 CSW=03000040
AP#0 IDR = 0x04770031 (AHB-AP var3 rev0)
ROM: Table BASE=0xe00ff000 SYSMEM=0x00000001, designer 43b Partno 4c0
0 0xe000e000: Generic IP component - Cortex-M0 SCS (System Control Space) (PIDR = 0x04000bb008  DEVTYPE = 0x00 ARCHID = 0x0000)-> cortexm_probe
CPUID 0x410cc601 (M0+ var 0 rev 1)
LPC11xx: Unknown IDCODE 0x4802302b
1 0xe0001000: Generic IP component - Cortex-M0 DWT (Data Watchpoint and Trace) (PIDR = 0x04000bb00a  DEVTYPE = 0x00 ARCHID = 0x0000)
2 0xe0002000: Generic IP component - Cortex-M0 BPU (Breakpoint Unit) (PIDR = 0x04000bb00b  DEVTYPE = 0x00 ARCHID = 0x0000)
ROM: Table END
***  1      LPC802 M0+
Ram   Start: 0x10000000, length     0x800
Flash Start: 0x00000000, length    0x4000, blocksize    0x400

**Comment by compuphase** [comment]
The above dump was for the LPC802, by the way.

**Comment by UweBonnes** [comment]
Thanks!

**Comment by UweBonnes** [comment]
Can you have a look at #884?

**Comment by compuphase** [comment]
Hello Uwe,

I have to dive into this. At the moment, I have no answer.

I remember having had the same error ("error erasing flash with vFlashErase
packet") once every while on the circuit I was using. On that circuit, the
"boot" pin was attached to an analog source. Which is why I dismissed those
errors at the time, assuming that the the microcontroller was occasionally
seeing the boot pin low after reset and using the wrong memory mapping.
Repeating the "load" command would upload the firmware.

Now that someone else has the same issue, and has it consistently, there
must be a different cause. I can't see anything wrong in the code at a
glance, so I have to do more testing. It could be a timing issue.

Thanks,
Thiadmer

**Pull request merged**
