### PR TITLE
fixup F103x8 flash size before build dfu iface string

### PR DESCRIPTION
**Pull request by zvova7890**
This fixes incorrect flash size in dfu iface string

### CODE REVIEW

**Comment by UweBonnes** [comment]
Argh, this code and this error is from me. Looking at the code now, I think this  fake deserves a compile time option with default: Compile the string with the flash size the chip announces and only if the user activates an additional option, change the the string for a 64 k device. Until now I have not heared of problems with the upper 64 k flash on a 64 k device, but there is no guarantee.

Any opinion?

**Comment by zvova7890** [comment]
Not sure. Because blackmagic is not feet in 64k, so user understand this in any way. After that he flash via SWDIO bootloader+firmware and then just want update firmware through DFU. I think if this can be an option, by default must allow "oversize"

**Comment by UweBonnes** [comment]
Please also fix the comment as proposed by Jiri.

**Comment by UweBonnes** [comment]
Please rebase into one commit.

**Pull request merged**
