### PR TITLE
Ftdi

### PR DESCRIPTION
**Pull request by UweBonnes**
Increase ftdi jtag speed.

### CODE REVIEW

**Comment by UweBonnes** [comment]
Gareth, please install libftdi1

**Comment by gsmcmullin** [comment]
Please update https://github.com/UweBonnes/blackmagic/blob/ftdi/.travis.yml#L7 so that CI build passes.

**Comment by UweBonnes** [comment]
Arg, correction:  linking against ftd1

**Comment by gsmcmullin** [comment]
This doesn't work for me.  It compiles and runs, but can't find a 1BitSy target on either JTAG or SWD.  I'm using the 'flossjtag' cable.  The current master head works correctly.

**Comment by UweBonnes** [comment]
I will split up and test more carefully. Please someone give me hints how to setup thetravis enging to  find and use a recent libftdi1.

**Pull request closed without merging**
