### PR TITLE
Make USBUART TX/RX async

### PR DESCRIPTION
**Pull request by Vestrel**
Allows to use gdb while sending data through UART. Seems to work on Maple mini.

### CODE REVIEW

**Comment by UweBonnes** [comment]
Can you please describe how to setup gdb/uart to see the blocking behaviour before your patch?

**Comment by Vestrel** [comment]
Start a debugging session in gdb (stop on breakpoint for example). Then connect to uart and start sending data non stop to bmp at baud rate below 250000. At baud rate 9600 gdb essentially halts.

**Comment by UweBonnes** [comment]
I now notice that you disable interrupts in you uart  routines. I feel this could cause colateral damage to an eventual running high speed SWO transfer. Do you really need to disable all interrupts? Perhaps you can selective disable IRQs. Or maybe use DMA?

**Comment by Vestrel** [comment]
Ready for review

**Comment by UweBonnes** [comment]
Scheduled for post 1.6.2

**Comment by Vestrel** [comment]
Rebased

**Comment by UweBonnes** [comment]
Did you really rebase and push? Please rebase to master so that travis succeeds. "git log --check" also shows whitespace errors and typos. Where is CM_ATOMIC_CONTEXT defined? Do you use a newer libopencm3? Is there any advantage for using those complicated #define functions like copy_from_fifo(). Doesn't gcc do a good job when used those a real functions and provide better type security?

**Comment by UweBonnes** [comment]
-vv please!

**Comment by Vestrel** [comment]
Didn't finish at the time. copy_from_fifo probably was overengineering on my part, removed. Whitespace corrected. As for CM_ATOMIC_CONTEXT: https://github.com/libopencm3/libopencm3/blob/8435287300e5ca9af9f889c529e7b1fa019c42fb/include/libopencm3/cm3/cortex.h#L278

**Comment by UweBonnes** [comment]
Missed CM_ATOMIC_CONTEXT in out libopencm3 branch. 

I compiled for stlink/st  with "make PROBE_HOST=stlink ST_BOOTLOADER=1 -j9" and after loading with stlink-tools I no longer get debug output on ACM1.

**Comment by UweBonnes** [comment]
It was a nucleo-F746ZG board, StlinkV2/1 and a f4_disco (V1 ) with RX/TX wired.

**Comment by Vestrel** [comment]
I'll investigate

**Comment by Vestrel** [comment]
My bad, introduced a bug in copy_from_fifo. Should work now.

**Comment by Azq2** [comment]
Thanks!
I had problems with the UART, if paste > 50 Kb of text in Picocom then receiving stops for a whole second.
I was already thinking of switching back to PL2303 ...

But after this commit issue fixed!

**Pull request merged**
