### PR TITLE
Target latest libopencm3 version

### PR DESCRIPTION
**Pull request by btashton**
Required fixes:
     * use usbd_request_return_codes -- commit 54b117c5a5767df8dc114612dfd8e8cb88b72c6b
     * drop deprecated timer_reset() -- commit 034dbf20ff8c54dcbee5238390b37a0d35180f44
     * drop 48 & 120 MHz configs -- commit a9dde2832eb8039b9e0d21a50b9b991ddbfc4e2d
     * ld scripts: drop duplication of standard sections -- commit 9a05dcb6c0aef712052d337457838f6041ffd57a

### CODE REVIEW

**Comment by UweBonnes** [comment]
With 
gcc version 8.3.1 20190703 (release) [gcc-8-branch revision 273027] (GNU Tools for Arm Embedded Processors 8-2019-q3-update) 

"make clean; make" gives:
platforms/common/cdcacm.c: In function 'cdcacm_set_config':
platforms/common/cdcacm.c:534:4: error: passing argument 4 of 'usbd_register_control_callback' from incompatible pointer type [-Werror=incompatible-pointer-types]
    cdcacm_control_request);
    ^~~~~~~~~~~~~~~~~~~~~~
In file included from include/gdb_if.h:25,
                 from platforms/common/cdcacm.c:30:
../libopencm3/include/libopencm3/usb/usbd.h:132:30: note: expected 'usbd_control_callback' {aka 'int (*)(struct _usbd_device *, struct usb_setup_data *, unsigned char **, short unsigned int *, void (**)(struct _usbd_device *, struct usb_setup_data *))'} but argument is of type 'enum usbd_request_return_codes (*)(usbd_device *, struct usb_setup_data *, uint8_t **, uint16_t *, void (**)(usbd_device *, struct usb_setup_data *))' {aka 'enum usbd_request_return_codes (*)(struct _usbd_device *, struct usb_setup_data *, unsigned char **, short unsigned int *, void (**)(struct _usbd_device *, struct usb_setup_data *))'}
        usbd_control_callback callback);
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~

**Comment by btashton** [comment]
@UweBonnes are you sure you updated the submodule to what is in this PR? That argument type is one of the fixes that I made and the CI is building this.

**Comment by UweBonnes** [comment]
I forgot to update the submodule. I see 180 Bytes more code with the stlink platform and about 110 for native This seems reasonable. On what platforms did you test?

And what is a good way to get back the old libopencm3 state ?

**Comment by btashton** [comment]
I usually use `git submodule update --recursive` as for testing on hardware, I have only done minimal so far. I have at least three of the targets I can test tonight, including the stm32f4discovery bmp and stlinkv2

**Comment by btashton** [comment]
I was able to do some testing of the BMP tonight and did not see any issues.  I looked in the bins for my stlink, but it looks like it might have been lost in my last move.

**Pull request merged**
