### PR TITLE
PSoC4: Initial additions/adjustments

### PR DESCRIPTION
**Pull request by mryndzionek**
This is the beginning of series of additions/adjustments aiming add adding basic Cypress PSoC4 chips support.

### CODE REVIEW

**Comment by mryndzionek** [comment]
Has this pull request a chance to be accepted? The first commit just adds a new command that could be useful elsewhere. The second shouldn't break anything.

**Comment by esden** [comment]
Thank you for your submission.

I am not comfortable with adding a function that retries 10 times to connect. This should never be necessary if the target is configured and set up correctly. Is there a specific reason why that would be necessary in any other context than problematic targets?

Also this should be possible to be done by running `mon swdp` and then pressing enter in GDB 10 times. Is Psoc that problematic to connect to?

**Comment by mryndzionek** [comment]
Please look at the PDF I linked in the commits:
http://www.cypress.com/documentation/programming-specifications/cybl10x6x-cy8c4127bl-cy8c4247b-programming-specifications
'4.3 Step 1 – Acquire Chip'

> The times of internal reset (<1 ms) and boot code (<100 µs)
are not specified exactly. Because they depend on the CPU
clock and the size of the code, they can vary in different revisions
of the chip.
In this case, the recommended way to enter Test mode is to
start sending an acquire sequence right after XRES is toggled
(or power is supplied in Power Cycle mode). This
sequence is sent iteratively until it succeeds; that is, all SWD
transactions are ACKed and all conditions are met. 

So yes, it's problematic. I know that there is another way. OpenOCD tries to use it, but it's also complex and less reliable. PSO4 is strange. For info you can look at:
http://dmitry.gr/index.php?r=05.Projects&proj=24.%20PSoC4%20confidential

**Comment by UweBonnes** [comment]
I don't have a PSOC4. Is your problem solved? If yes, how?

**Comment by mryndzionek** [comment]
Oh sorry. I forgot that this branch is a pending PR. I've forced pushed to sync and pull from master and this closed the PR. This isn't urgent right now. I have the changes on my clone. I'll re-open the PR if I figure out some other solution.

**Pull request closed without merging**
