### PR TITLE
Allow flashing all of the H750's first flash bank.

### PR DESCRIPTION
**Pull request by hydra**
See also #632

### CODE REVIEW

**Comment by UweBonnes** [comment]
Probably the compiler will notice, but pull the setup for the first bank befor the test and with the test either add the DEBUG or the second bank.

**Comment by hydra** [comment]
yes good call, DRY!  Done as requested.   LGTM!

**Comment by UweBonnes** [comment]
Can you please test #645?

**Comment by hydra** [comment]
Tested, #645 is OK on STMH750VBT6 for me.  I can erase the flash and upload code OK.

**Comment by UweBonnes** [comment]
Superseeded bu #639

**Comment by UweBonnes** [comment]
Superseeded by #645

**Comment by UweBonnes** [comment]
Superseeded by #645

**Pull request closed without merging**
