### PR TITLE
Speed up bitbanging SWD/JTAG

### PR DESCRIPTION
**Pull request by UweBonnes**
By pulling the bitbang action into the high level JTAG/SWD commands, substantial speedup and better setup/hold and high times are achieved. For native,stlink and swlink SWD turnaround  has also some speedup by using direct register access against the generalized libcm3 high level functions.

### CODE REVIEW

**Comment by korken89** [comment]
Tested with the following results:

* With a 40k binary I get 33 kb/s with the patch applied vs 23 kb/s on master
* With a 100k binary I get 44 kb/s with the patch applied vs 24 kb/s on master

**Comment by UweBonnes** [comment]
Close and reopen to trigger travis run

**Comment by UweBonnes** [comment]
reopen to trigger travis run

**Comment by gsmcmullin** [comment]
This works for me.  I think the small compromise in readability is worth the improved performance.

**Comment by joric** [comment]
Came here from #320 - the TMS floating feature (now closed) works like a charm on my YJ-14015 (Core-nRF51822) module ([mitosis-bluetooth](https://github.com/joric/mitosis/tree/devel/mitosis-bluetooth)), so, thanks! Disconnecting wires every time was very frustrating, considering those bluetooth modules love powering off and detaching for every small cause.

**Pull request merged**
