### PR TITLE
Use pkg-config to get CFLAGS & LDFLAGS for libftdi1

### PR DESCRIPTION
**Pull request by DanielO**

### CODE REVIEW

**Comment by sidprice** [comment]
The use of pkg-config will break the build for Windows.

**Comment by DanielO** [comment]
> The use of pkg-config will break the build for Windows.

Is there an existing "this is a windows build" variable in the Makefile? It could be conditioned on that.

**Comment by UweBonnes** [comment]
@Sid: My mingw cross compile setup has pkg:
> locate pkg | grep mingw|grep ftdi
/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig/libftdi1.pc
> rpm -qf /usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig/libftdi1.pc
mingw64-libftdi1-devel-1.2-lp150.1.55.noarch

Are you perhaps missing some p[ackages?
Are you perhaps miss

**Comment by UweBonnes** [comment]
> rpm -qf /usr/x86_64-w64-mingw32/sys-root/mingw/share/pkgconfig
mingw64-filesystem-20190529-lp150.1.1.noarch

I can cross-compile #535 with "mingw64-make PROBE_HOST=libftdi"

**Comment by UweBonnes** [comment]
@DanielO: Can you commit --amend some reference to this pull request to your patch?
That way I can "Rebase and merge" with only one commit against "Create a merge commit" creating two commits.

**Comment by DanielO** [comment]
OK done.

**Comment by sidprice** [comment]
@UweBonnes , I am out of office this morning, but will do a test this afternoon.

**Comment by sidprice** [comment]
@UweBonnes found a little time so I tried to build pc-stlinkv2 and pc-hosted and both build fine on my Windows 10 PC with mingw.

Sorry it was my mistake when I tried to run pkg-config yesterday.

**Comment by sidprice** [comment]
@UweBonnes also just build libftdi.

**Pull request merged**
