### PR TITLE
STM32L07x

### PR DESCRIPTION
**Pull request by beewoolie**
Added STM32L07x's to the supported MCUs.

o Some regularizing of the target detection was done between L1's and L0's.
o New command for MCU info added to aid in determining which MCU we're using.

### CODE REVIEW

**Comment by beewoolie** [comment]
Looks like there may be a catch.  The patch allows the L07x's to write to flash, but something goes wrong when the file being written approaches 64KiB.  I'll invetigate and update the patch accordingly.

**Comment by UweBonnes** [comment]
41fb2a310475263d6d855862adfb26867c7a3f1c adds more L0 devices. Writing above 64 k is still a problem. See "STM32L0: Timeout when erasing large chunks of flash" on the mailing list.

**Comment by esden** [comment]
@UweBonnes is the large chunk flash erase the known GDB timeout problem?

**Comment by schodet** [comment]
Hello,

I also see the 64 Kb problem, actually, the problem is with the erase command, there is something wrong if it is done in one go.

I can make it work if I split the flash definition in 64 Kb parts.

**Comment by schodet** [comment]
More precision on the > 64 Kb problem:

If programming a 70 Kb binary for example, GDB first erase, then write. When writing the first block at address 0x8010000, the MCU signals a "not erase" error. Actually the erase done in one go did not erase this block.

When programming a small binary at 0x8010000 directly, there is no problem.

I tried to put a loop in `stm32lx_nvm_prog_erase` around the whole function content, to program 64 Kb per 64 Kb, but it does not solve the problem.

If I declare separated blocks to GDB, I suppose it issues several erase commands and everything works.

You can see #246 for the code I use.

**Comment by gsmcmullin** [comment]
What version of GDB is this problem being observed?  There is a known bug in GDB 7.12 where it times out on the flash erase packet.  See #181

**Comment by schodet** [comment]
It's GDB 7.7.1, but there is no timeout, the problem is with the erase which do not erase.

Actually, I think we are supposed to wait after each erase operation, the current code erase every page in one go.

The commit 2216587 (in master) workarounds the problem by defining 3 different flash sections.

**Comment by esden** [comment]
As this issue has been fixed in master I am closing this pull request.

If there is still an issue please feel free to reopen this pull request. :)

**Pull request closed without merging**
