### PR TITLE
Add support for STM32WLxx

### PR DESCRIPTION
**Pull request by fabiobaltieri**
This adds support for the STM32WL series in stm32l4.c. These parts have the same flash registers layout as the L4 series, but a different base. Since there are already two sets of registers in this target file, this adds support for register maps that can be customized for each device ID.

Tested it on a Seed LoRa-E5, that's based on the STM32WLE5, the single core version of the WL55. Unfortunately it looks like ST left the second core AP configured on the single core part, and the probe hangs when probing it. I currently hacked my way around it by making it only probe the first AP and the flash and debugging capabilities seems to work fine, I'll have to figure how work around that cleanly, but this should work fine on the WL55.

### CODE REVIEW

**Comment by UweBonnes** [comment]
Fabio, the problem with the second AP should be solved. We discussed before and I asked you for a test, but I got no response. Otherwise , how does your PR compare to #458? Also please consider the discord channel for discussion.

**Comment by fabiobaltieri** [comment]
Hi Uwe, don't you discussed it with me, this is my first patch to the project... anyway I'm running whatever is upstream now and it still hangs:

> AP   0: IDR=24770011 CFG=00000000 BASE=e00ff003 CSW=23000040 (AHB-AP var1 rev2)
> AP   1: IDR=84770001 CFG=00000000 BASE=f0000003 CSW=43800040 (AHB-AP var0 rev8)
> Timeout during scan. Is target stuck in WFI?
> SW-DP scan failed!

What do you want me to test?

As for #458, I'd say it compares pretty badly, different chip, different offset support strategy... you tell me, I'd say this one is cleaner.

**Comment by UweBonnes** [comment]
Sorry, I mixed up names. There is discussion around that also in #832

**Comment by UweBonnes** [comment]
Did you check that your construct does not need static ram? Does providing  those static register structures result in less flash usage than calculating the addresses on the fly? Otherwise the additional operation  will not hamper programming speed substantial and should be taken for the sake of reduced flash usage.

**Comment by fabiobaltieri** [comment]
That is a very good point, they were indeed using more SRAM, I've set them as `const` and updated the PR so they don't take RAM anymore.

The flash and ram usage for native are the following, on current master:
```
Memory region         Used Size  Region Size  %age Used
             rom:      126400 B       128 KB     96.44%
             ram:        3560 B        20 KB     17.38%
```

after this patch:
```
Memory region         Used Size  Region Size  %age Used
             rom:      126188 B       128 KB     96.27%
             ram:        3560 B        20 KB     17.38%
```

It does look like flash usage goes down, stm32l4.o data goes from 3296 to 3084 bytes on my build.

As for programming speed, I don't think it's going to be affected since these are only going to be used for setting up the flash controller if I understand correctly, but I don't quite have a convenient way to compare. This is what I'm observing right now:

```
Start address 0x08002df0, load size 84422
Transfer rate: 34 KB/sec, 827 bytes/write.
```

Does it look reasonable?

**Pull request merged**
