### PR TITLE
add support for baite stlink-v2 clone

### PR DESCRIPTION
**Pull request by cuvoodoo**
betemcu/baite offers a ST-LINK/V2 clone with SWD, JTAG, and SWIM
support.
this dongle was detected as ST-LINK/V1 because PC13 was not pulled
low.
this change verifies if the LED is on PA9 to correct this wrong
identification.

### CODE REVIEW

**Comment by UweBonnes** [comment]
I think, checking PB11 is pulled high is a better test, as discussed in #504. The pullup is 620 Ohm, so it will win in all cases against the built-in pulldown when activated. As the LED has a quite high flow voltage, the voltage on th baite PB9 is probably in the dis-allowed range.

**Comment by UweBonnes** [comment]
Can you please check https://github.com/UweBonnes/blackmagic/tree/baite?

**Comment by cuvoodoo** [comment]
> I think, checking PB11 is pulled high is a better test, as discussed in #504. The pullup is 620 Ohm, so it will win in all cases against the built-in pulldown when activated. As the LED has a quite high flow voltage, the voltage on th baite PB9 is probably in the dis-allowed range.

Agreed. Checking PB11 would identify ST/LINK V2 boards with SWIM support.
This includes the baite, and would work for any mini stlink v2 (the small clone dongles with aluminium case) which would not already be detected as v2.
This is also the check I do in PR #498.

**Comment by cuvoodoo** [comment]
> Can you please check https://github.com/UweBonnes/blackmagic/tree/baite?

Looks good.
I also does not mis-identify the ST-Link V1
I will close this PR once you opened one with your changes.

**Comment by cuvoodoo** [comment]
the alternative change has been committed in #519

**Pull request closed without merging**
