### PR TITLE
Tidying of common swdp access functions

### PR DESCRIPTION
**Pull request by mubes**
Some tidying of the common swdp access functions. This will change the timing slightly so does need to be tested against relevant targets, but is fine on BMP.

### CODE REVIEW

**Comment by UweBonnes** [comment]
Unrelated whitespace changes and changes in High and setup times to smaller margins not justified.

**Comment by mubes** [comment]
Timings extended to align with previous version ( although they were already in line with the ARM timing specified in http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0517b/CIHBIEHF.html ). Whitespace should be addressed through a tool. I will submit a patch for that.

**Comment by UweBonnes** [comment]
Also timing is adequate and even reliable when going off-board with jumper wire, people often misstake problems by flacky connections and/or  flaky hardware as timing problems, e.g. see #452 and #392. The slightly increased margins only slow down a little but for sure increases margins.

**Comment by UweBonnes** [comment]
Superceeded by #721

**Pull request closed without merging**
