### PR TITLE
Additional EFM32 support

### PR DESCRIPTION
**Pull request by richardeoin**
Add recent parts PG12B, JG12B, GG11B, TG11B, GG12B (Issue [#435](https://github.com/blacksphere/blackmagic/issues/435))

Support recovering locked parts (Issue [#436](https://github.com/blacksphere/blackmagic/issues/436))

### CODE REVIEW

**Comment by UweBonnes** [comment]
Adding all variants may be a tedious job. Is there perhaps a more general way to recognize ESP32 chips?

**Comment by richardeoin** [comment]
This pull adds some new *families*, not variants. Tracking all variants across this product line would indeed be a sisyphean task - there are 430 distinct parts in stock at DigiKey right now, and many hundreds more available from factory stock.

Unfortunately we can't check the TARGETID register. The DP is a DPv1, so there is no TARGETID register.

Silabs change the MSC address, MSC layout, user data region size and bootloader region size between families. We need to track these in order to write to flash correctly.

**Comment by UweBonnes** [comment]
Did anybody work with this patch?

**Comment by UweBonnes** [comment]
Rebased and applied as #567

**Pull request closed without merging**
