### PR TITLE
add push-pull on srst to miniv2

### PR DESCRIPTION
**Pull request by konsgn**
Self-explanitory I hope.

### CODE REVIEW

**Comment by konsgn** [comment]
But we aren't tying high, we are just saying that when srst(stm32 state) is high, output 3.3v rather than float. When srst goes low, it will then output a 0 v which will assert reset on target too.


The problem is that with open-drain mode, on srst, we pull low and targets reset is asserted, but when we set it high, there is no pull up between the srst pin and the buffer, so it floats. That is not a condition that you should put to buffer.


What do you think?


PS: I also added a -Wignore to src/Makefile to get the code to compile under gcc8


Science!
________________________________

**Comment by UweBonnes** [comment]
Well, the SRST line needs a pull up. And the SRST must be open collector. So activate the internal pull up on SRST when SRST is idle from the BMP line.

**Comment by UweBonnes** [comment]
line -> side

**Comment by konsgn** [comment]
The issue is that there is a buffer between the target and the bmp uC. I've had a situation where the float state of the stm32(bmp) was somehow seen as low input to the buffer, and the reset line of the target was held low regardless of the bmp's srst state. 

Crap, it may be that the buffer I use has "bus hold circuits" (fxla108) that make the internal pull-up of the chip not strong enough to switch directions on the buffer.

**Pull request closed without merging**
