### PR TITLE
Symbolic definition and remapping of USB endpoints

### PR DESCRIPTION
**Pull request by sidprice**
All USB endpoints for BMP are symbolically defined.

The addresses for the endpoints are remapped to place the GDB and TraceSWO endpoints in the first four endpoints of the platform MCU.

The USB UART endpoints are mapped after the above endpoints.

This arrangement allows platforms based upon the STM32F4xx to support GDB and SWO ports and allows the native BMP platform to additionally offer the USB UART port.

The native platform was tested on Windows and Linux (Ubuntu), however an F4Discovery platform was not available for test.

Please verify F4Discovery if one is available.

### CODE REVIEW

**Comment by UweBonnes** [comment]
Sid, as Dave pointed out, your change will be a pita for existing applications using SWO on the BMP. So your change may only thouch your platform and the f4discovery.

**Comment by sidprice** [comment]
Understood. 

However, what I propose is that the symbolic definitions of the endpoints are retained and that they be defined in platform.h. Would that be acceptable?

**Comment by UweBonnes** [comment]
Has this patch still use for you? If yes, rebase to master so that the merge commit messages disappear. otherwise  the tmc4 platform compiled for me with make all_platforms. What is needed to get that error?

**Comment by sidprice** [comment]
@UweBonnes This so long ago, I need to revisit the code base. I will let you know if this is still a valid PR.

**Comment by UweBonnes** [comment]
Please close if no longer needed. Reopen if sometimes needed in the future.

**Comment by sidprice** [comment]
OK, will do.

**Comment by UweBonnes** [comment]
This PE is still open...

**Comment by sidprice** [comment]
Yes, I have not had time to double check. Please give me some time.

**Comment by sidprice** [comment]
I am going to close this and if I really need something like it I will create a new PR.

**Pull request closed without merging**
