### PR TITLE
Add LPC546xx support.

### PR DESCRIPTION
**Pull request by eivindbergem**
Added support for LPC546xx. Code based of off LPC43xx target.

I've tested it on an LPC54628J512ET180 using the hosted platform with a J-link.

### CODE REVIEW

**Comment by eivindbergem** [comment]
#553

**Comment by UweBonnes** [comment]
Please squash into one commit.

**Comment by eivindbergem** [comment]
Did you mean #553? Not sure why #595 is relevant.

**Comment by UweBonnes** [comment]
Argh, bad typing, Of cource #553!

**Pull request merged**
