### PR TITLE
Pc stlinkv2

### PR DESCRIPTION
**Pull request by UweBonnes**
Mostly pc-stlinkv2 changes:
- detect stlink attach/detach
- fix crash with some dongle connected but dongle with other serial requested
- Abort early when setting up AP0 fails
- Abort with DP errors
- Fix read/write CPU register

### CODE REVIEW

**Comment by zardam** [comment]
I'm sorry, but I still cannot connect to a protected SAMD21.

When protected : 

```
(gdb) mo sw
Target voltage: ABSENT!
Available Targets:
No. Att Driver
 1      ARM Cortex-M M0+
(gdb) at 1
Attaching to Remote target
Attaching to Remote target failed
```

Debug output :

```
AP   0: IDR=04770031 CFG=00000000 BASE=41003003 CSW=03000040
ROM: Table BASE=0x41003000 SYSMEM=0x0
�?0 Entry 0x9f0fc002 -> Not present
�?1 Entry 0x3002 -> Not present
�?ROM: Table END
-> cortexm_probe forced
```

**Comment by UweBonnes** [comment]
As far as I understand tje protected SAMD, you need to connect under reset. I do not see that in the trace above. Nor what Platform you use.

Please try with #507, as that reworks connect under reset and other things.

**Comment by zardam** [comment]
With #507, I cannot even list the board:

```
(gdb) mo sw
Target voltage: ABSENT!
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
```

```
AP   0: IDR=04770031 CFG=00000000 BASE=41003003 CSW=03000040
cortexm_prepare
```

I'm using PROBE_HOST=swlink on a "blue pill". The board under debug is an Arduino zero clone (https://startingelectronics.org/articles/arduino/wemos-arduino-m0/).

Connect under reset is not needed. When the SAMD is protected and a debugger is connected, the CPU is held in "extended reset" at startup, and you can talk with the "Device Service Unit".

The only thing I have to do with my working branch is to manually reset the board after connecting the debugger, just before trying to list it.

**Comment by UweBonnes** [comment]
Zardam,

can you comment out the "cortexm_prepare()" call?

Then look if something like
`ROM: Table BASE=0xe00ff000 SYSMEM=0x1
0 0xe000e000: Generic IP component - Cortex-M3 SCS (System Control Space) (PIDR = 0x4001bb000)-> cortexm_probe`

appears. If we can read  the PIDR at this stage and decode right, we will know it is a Atmel chip and do the right thing.

**Comment by zardam** [comment]
I changed cortexm_prepare() to always return true. With the protected SAMD:

```
(gdb) mo sw
Target voltage: ABSENT!
SW-DP scan failed!
```
```
AP   0: IDR=04770031 CFG=00000000 BASE=41003003 CSW=03000040
AP0 PIDR 0x0009fcd0, designer 0x1f
ROM: Table BASE=0x41003000 SYSMEM=0x0
�?0 Entry 0x9f0fc002 -> Not present
�?1 Entry 0x3002 -> Not present
�?ROM: Table END
cortexm_release, DEMCR 0, apsel 0
```

**Comment by UweBonnes** [comment]
This looks good!
We can read 12.13.13 Peripheral Identification 0 and  1 as we expect for a SAMD (0x1f and 0xcd0). As the device is  protected, we will not see the normal cortexm parts, adiv5_component_probe will fail nd sampdprobe not called in the normal way. But in the failing  case, we can check for the PIDR of a SAMD and  call samd_probe() explicit.

**Comment by UweBonnes** [comment]
Please update #507. It should (famous last words) now finally find the protected SAMD. If it still does not, have a look at the code. I have no SAMD her to test myself, so small error may still be there,

**Comment by zardam** [comment]
Sorry for the bad news, I just tried, and it does not work. I also tried to probe a non protected SAMD without success. I will try to check the code and get it working, maybe this week end.

**Comment by zardam** [comment]
Ignore my previous statement about the failure with the unprotected SAMD, it is working. I'm still working on a fix for the protected case.

**Pull request merged**
