### PR TITLE
Support for flashing and debugging Texas Instrument MSP432P401x MPUs

### PR DESCRIPTION
**Pull request by newbrain**
Hi,
Thanks for this excellent tool!

I thought adding support for the TI MSP432P401 family could be an useful enhancement.
Flash buffering has been fixed at 1024 bytes.
Both flashing and debugging seem to work correctly.

Two extra commands have been added:
-  monitor **erase**: erase the entire Main Flash, leaving alone Info Flash with bootloader and device calibration.
- monitor **sector_erase \<address\>**: erases just the sector (4096 bytes) that contains \<address\>, also in Info Flash.

Test Hardware:
- Target: MSP432 Launchpad Red
- Platform: STM32f103 "BluePill" (stlink platform)

Test Software:
- gdb on Windows, Linux and the Windows Linux Subsystem (native Ubuntu/bash in Windows10).
- VisualGDB, Visual Studio extension for gdb.

Limitations:
- Only silicon Rev. C and later are supported, as Rev B does not include flash routines in ROM.
- The board needs a manual reset to work 100% under debug.

### CODE REVIEW

**Comment by newbrain** [comment]
No interest? No problems: honestly, they are not very popular MPUs.
I'm probably going to add NXP Kinetis KE04 shortly.
Anyone interested?

**Comment by UweBonnes** [comment]
There is interest! However patch application policy at the moment is sub-optimal. I will try to get the mantainers to be more responsive.

**Comment by gsmcmullin** [comment]
@newbrain Please reformat with Linux kernel coding style and I'll merge.  It looks good, thank you.

**Comment by newbrain** [comment]
I rebased my branch on the latest master, and changed the code due to pull request #302.
I also reformatted according to Linux kernel style, some lines is still >80 char, but as far as I can see from the rest of the codebase that seems to be acceptable.

**Comment by UweBonnes** [comment]
https://github.com/newbrain/blackmagic/branches shows 6 changed commits, while I guess there is only one relevant commit. Please rearrange/rebase/??? so that there is only one commit difference. Thanks.

**Comment by newbrain** [comment]
Something horrible happened -my fault- to my git repo, and took me some time to unravel (with qualified help).
I'm sorry for the hassle, and I have a created a new, clean, pull request containing a single commit as requested: #353.
I'll close this one, again, my apologies.

**Pull request closed without merging**
