### PR TITLE
Add HydraBus support

### PR DESCRIPTION
**Pull request by gsmcmullin**
Supersedes #67.

- Squashed commits so we don't have ST binary stuff in the history.
- Updated to match the platform refactoring.
- Removed Windows .bat file and updated platform readme with the command.

### CODE REVIEW

**Comment by gsmcmullin** [comment]
retest this please

**Comment by gsmcmullin** [comment]
@bvernoux please confirm this still works on the Hydrabus hardware.

**Comment by bvernoux** [comment]
I'm looking in trunk and in src\platforms there is no hydrabus why ?
Where it is merged ?
See https://github.com/blacksphere/blackmagic/tree/master/src/platforms

**Comment by gsmcmullin** [comment]
https://github.com/gsmcmullin/blackmagic/tree/hydrabus/src/platforms

It isn't merged.  I'll merge it when you confirm it works.

**Comment by bvernoux** [comment]
Hi,
 Could you fix the Readme.md How to Build for hydrabus (as I have no right
to push) and it's really minor

How to Build
============
```
cd blackmagic
cd ./libopencm3
make
cd ..
cd ./src
make PROBE_HOST=hydrabus
```

**Comment by bvernoux** [comment]
Do you have any news about to add HydraBus support in master ?

**Comment by gsmcmullin** [comment]
You said there is a problem with the bootloader.  I don't have your hardware, so I can't test and debug it.
Would you like me to merge this as is, and then you send me another PR with the bootloader fix?

**Comment by bvernoux** [comment]
Yes if you can merge it then I will do a PR with the fixes
If you want I can send you freely an HydraBus board just send me an Email with your addr at bvernoux@hydrabus.com
Thanks for all

**Pull request merged**
