### PR TITLE
esp8266 port

### PR DESCRIPTION
**Pull request by markrages**
For wireless debugging.

See Readme.md for details.

### CODE REVIEW

**Comment by gsmcmullin** [comment]
Hi Mark

Sorry for the delay.  I haven't merged this because it's breaking my build, having added another build dependency.  Please apply the patch below to make it a little more self contained.  Once the automated build passes, I'll merge.

```diff
diff --git a/.gitignore b/.gitignore
index a40d44d..ffa0d21 100644
--- a/.gitignore
+++ b/.gitignore
@@ -16,4 +16,5 @@ tags
 *.b#*
 blackmagic_upgrade
 *.exe
+src/platforms/esp8266/esp-open-rtos
 
diff --git a/src/platforms/esp8266/Makefile.inc b/src/platforms/esp8266/Makefile
index 9bc3b16..6513ee5 100644
--- a/src/platforms/esp8266/Makefile.inc
+++ b/src/platforms/esp8266/Makefile.inc
@@ -1,5 +1,5 @@
 # -*-Makefile-*-
-RTOS_PATH=~/src/esp8266/esp-open-rtos
+RTOS_PATH=$(PLATFORM_DIR)/esp-open-rtos
 ESPPORT = /dev/ttyFTDI_CABLE_TX
 ESPBAUD = 230400
 
@@ -31,10 +31,15 @@ FIRMWARE_DIR = platforms/esp8266/firmware/
 
 EXTRA_COMPONENTS=extras/dhcpserver
 
+$(PLATFORM_DIR)/Makefile.inc: $(RTOS_PATH)
+
+$(RTOS_PATH)/common.mk:
+       git clone --depth=1 https://github.com/SuperHouse/esp-open-rtos $(RTOS_PATH)
+
 include $(RTOS_PATH)/common.mk
 
 host_clean:
-       $(Q) rm -rf $(BUILD_DIR) $(FIRMWARE_DIR)
+       $(Q) rm -rf $(BUILD_DIR) $(FIRMWARE_DIR) $(RTOS_PATH)
 
 debug_shell: flash
        miniterm.py $(ESPPORT) 460800
```

**Comment by OpenUAS** [comment]
Much appreciated if it can be fixed

**Comment by strongly-typed** [comment]
Hi Gareth,
hi Mark,

Great work so far!

I'm using [CircleCI](https://circleci.com/gh/strongly-typed/blackmagic) with a [Docker container](https://hub.docker.com/r/malachib/esp-open-rtos/) for the [esp-open-sdk](https://github.com/pfalcon/esp-open-sdk) and [esp-open-rtos](https://github.com/SuperHouse/esp-open-rtos) to build the binaries for the ESP8266. This avoids building the toolchain in TravisCI from source.

With the artifacts from CircleCI I was able to flash a ESP8266 to become a Wifi-enabled black magic probe.

    ./esptool.py \
        -p /dev/tty.wchusbserial1420 --baud 230400 \
        write_flash -fs 32m -fm dio -ff 40m \
            0x0000 ~/Downloads/0x0000_rboot.bin \
            0x1000 ~/Downloads/0x1000_blank_config.bin \
            0x2000 ~/Downloads/0x2000_blackmagic.bin

Result is:

    WARNING: Flash size arguments in megabits like '32m' are deprecated.
    Please use the equivalent size '4MB'.
    Megabit arguments may be removed in a future release.
    esptool.py v2.2-dev
    Connecting....
    Detecting chip type... ESP8266
    Chip is ESP8266EX
    Uploading stub...
    Running stub...
    Stub running...
    Changing baud rate to 230400
    Changed.
    Configuring flash size...
    Flash params set to 0x0240
    Compressed 3104 bytes to 2169...
    Wrote 3104 bytes (2169 compressed) at 0x00000000 in 0.1 seconds (effective 203.9 kbit/    s)...
    Hash of data verified.
    Compressed 2048 bytes to 23...
    Wrote 2048 bytes (23 compressed) at 0x00001000 in 0.0 seconds (effective 615.8 kbit/    s)...
    Hash of data verified.
    Compressed 334496 bytes to 235802...
    Wrote 334496 bytes (235802 compressed) at 0x00002000 in 10.9 seconds (effective 246.0     kbit/s)...
    Hash of data verified.
    
    Leaving...
    Hard resetting...
    
With this ESP8266-BMP I was able to connect with arm-none-eabi-gdb over Wifi and flash a simple blinky to a STM32F103 on a blue pill:

    arm-none-eabi-gdb \
        -ex "target extended-remote 172.16.0.1:2000" \
        -ex "monitor swdp_scan" \
        -ex "attach 1" \
        -ex "load" /tmp/xpcc/build/stm32f103_blue_pill/blink/blink.elf \
        --batch

Result is

    Target voltage: not supported
    Available Targets:
    No. Att Driver
     1      STM32F1 medium density
    _delay_ms (ms=ms@entry=100) at /private/tmp/xpcc/build/stm32f103_blue_pill/blink/libxpcc/generated_platform/driver/core/cortex/delay.cpp:54
    54		while (int32_t(DWT->CYCCNT - start) < delay)
    Loading section .reset, size 0xec lma 0x8000000
    Loading section .text, size 0x574 lma 0x80000f0
    Loading section .rodata, size 0x40 lma 0x8000664
    Loading section .fastcode, size 0x54 lma 0x80006a4
    Loading section .fastdata, size 0xc lma 0x80006f8
    Loading section .table.zero.intern, size 0x8 lma 0x8000704
    Loading section .table.copy.intern, size 0xc lma 0x800070c
    Loading section .table.section_heap, size 0xc lma 0x8000718
    Start address 0x800020c, load size 1824
    Transfer rate: 4 KB/sec, 202 bytes/write.    

Credits go to @daniel-k for fixing some issues with the port, to @malachi-iot for providing the Docker container, and to @salkinium for pointing me to CircleCI.

Would it be doable to rely on CircleCI for building for the ESP8266 and not caring about TravisCI for ESP8266?

**Comment by markrages** [comment]
I moved my changes to a branch https://github.com/markrages/blackmagic/tree/esp8266 and it automatically closed this PR.  I shall open a new one when I get the esp8266 build working again.

**Pull request closed without merging**
