### PR TITLE
stm32_mem.py: Print longer strings and small formatting changes.

### PR DESCRIPTION
**Pull request by UweBonnes**

### CODE REVIEW

**Comment by gsmcmullin** [comment]
I have no problem with the Python changes.  A change to libopencm3 is significant and shouldn't be sneaked in here.  Also, the libopencm3 commit referenced doesn't seem to exist upstream.

**Comment by gsmcmullin** [comment]
This doesn't work for me:
```
USB Device Firmware Upgrade - Host Utility -- version 1.2
Copyright (C) 2011  Black Sphere Technologies
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

Device ID:     1d50:6017
Manufacturer:     Black Sphere Technologies
Product:     Black Magic Probe (Upgrade)
Serial:         D5DEA7E4
Traceback (most recent call last):
  File "./scripts/stm32_mem.py", line 200, in <module>
    data = stm32_read(dfudev)
  File "./scripts/stm32_mem.py", line 63, in stm32_read
    data = dev.upload(2, 1024)
  File "/home/gareth/Projects/blackmagic/scripts/dfu.py", line 102, in upload
    length, value=wBlockNum, index=self.index) 
  File "/home/gareth/.local/lib/python2.7/site-packages/usb/legacy.py", line 211, in controlMsg
    timeout = timeout)
  File "/home/gareth/.local/lib/python2.7/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/home/gareth/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/home/gareth/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```
Remember we have old bootloaders out there that don't support upload.  Support for upload must be checked in the DFU function descriptor before attempting to use it.

**Comment by UweBonnes** [comment]
I did not yet find a way to retrieve bmAttributes of the DFU descriptor from the device.  A workaround could be some read, protected by try/except at the beginning and only verify when read was successfull. I will load an old bootloader and test next week,

**Comment by UweBonnes** [comment]
The lastest patches try to read the devices and catch eventual exception.

**Pull request merged**
