### PR TITLE
add Dockerfile and build.sh script

### PR DESCRIPTION
**Pull request by zoobab**
add Dockerfile and build.sh script, this builds and copies the artifacts *.bin to the root directory.

### CODE REVIEW

**Comment by zoobab** [comment]
Any update?

**Comment by gsmcmullin** [comment]
I don't really understand the point of this.
@UweBonnes This may be useful for you to get libftdi1 in CI by doing the build in Docker in Travis.

**Comment by UweBonnes** [comment]
@zoobab : Can above dockerfile use a recent libftdi1? Can you help me to use libftdi1?

**Comment by zoobab** [comment]
With some mods, it can use another libftdi1. Which one do you want?

**Comment by UweBonnes** [comment]
A recent one, allowing asynchronous transfers.

**Comment by UweBonnes** [comment]
The rationale of this PR is not clear. We have CI and a  place with daily builds. Closing for now.

**Comment by zoobab** [comment]
"We have CI and a place with daily builds."

It does not work on my laptop.

And 3 years for a pull request?

**Comment by UweBonnes** [comment]
CI runs on github. "make all_platforms" runs on the local CPU and fills ./artifacts. What are you missing?

**Comment by sidprice** [comment]
What is missing is the environment that allows "make all_platforms" to actually do the build. The user must have all the tools installed and if on Windows that is not an insignificant task.

**Comment by UweBonnes** [comment]
Please try with recent git head. HOSTED_BMP_ONLY=1 is now default for the HOSTED build and should succeed on windows too

**Comment by sidprice** [comment]
What about building the BMP firmware and LOCM3? Do those "just work" on Windows?

A Docker solution would be a good step forward removing one more "barrier to entry" for others.

**Comment by UweBonnes** [comment]
Okay, now there is a better rationale for this PR. Allow local docker build, while local system may have problems to  build. I would accept a PR with two constraints: - Should work on  recent git head - Pr creator should give some promise to keep things updated.

It would have helped, if more info and explication would have been given earlier. Do not expect the other side to understand condensed facts.

Regarding Sids windows argument. Please tell if hosted HOSTED_BMP_ONLY build on windows or  at least report error or better provide a PR if few things need change or discuss in advance if larger changes are neede. That way, with a recent downloaded firmware and hosted all target development can done. It this really a big hurdle?

**Comment by sidprice** [comment]
@UweBonnes I just took a look at the docker file and I am not sure it does what I was expecting. 

My understanding of such files is that they encapsulate a build environment that is isolated from the host computer, and possibly in a cross platform manner. @zoobab does your file do this? A quick glance at it says probably not :(

**Comment by UweBonnes** [comment]
Sid, can you verify my reasoning about current hosted being much more easier to build on windows now?

**Comment by sidprice** [comment]
@UweBonnes Unfortunately, I just got a new laptop and I do not have GCC installed, only GCC ARM. I will install it and test later, in a day or two.

**Pull request closed without merging**
