### PR TITLE
Frequency

### PR DESCRIPTION
**Pull request by UweBonnes**
Implement SWJ frequency setting (#321, #392, #452)

While most problems with unreliable SWJ connections are better handled by a better cable connection, there are cases where explicit SWJ frequency setting are needed:
- Adapter capable of very high speed (e.g. ST-Llink V3) where startup default should be moderate, but possibility to go to higher frequencies may be welcome
- devices that have SWJ restrictions (e.g AVR8 where JTAG freq must be > f(clock) / 8)
- testing

### CODE REVIEW

**Comment by lATAl** [comment]
Hi @UweBonnes, how to use this command? Try `mon frequency 900k` but it show
Target does not support this command.

**Comment by lATAl** [comment]
@UweBonnes 
Yes. Black Magic Probe (Firmware v1.7.1)

**Comment by UweBonnes** [comment]
1.7.1 ha about 200 patches. Check your patcj level

(gdb) mon vers
Black Magic Probe(STLINK-V3) v1.7.1-203-g37c49d81-dirty, Hardware Version 0
...
(gdb) mon help
General commands:
        version -- Display firmware version info
        help -- Display help for monitor commands
        jtag_scan -- Scan JTAG chain for devices
...
(gdb) mon freq 900k
Max SWJ freq 0018f80b

**Comment by lATAl** [comment]
@UweBonnes I see it now. Maybe the version I downloaded on the releases page is out of date.
Thank you.

**Comment by UweBonnes** [comment]
Autsch, it seems the daily build does not update any more.

**Pull request merged**
